import { expect, test } from './fixtures';

test('visit feedback disables saving and collapses deleted history without replacing the form', async ({ page }, testInfo) => {
  await page.goto('/');
  if (testInfo.project.name.startsWith('mobile')) await page.getByRole('button', { name: 'List', exact: true }).click();
  await page.locator('[data-airport="KBVS"]').click();
  await page.getByLabel('Notes', { exact: false }).fill('Retain this visit during confirmation');
  const button = page.locator('#checkin button[type="submit"]');
  const before = await button.boundingBox();
  await button.click();
  await expect(button).toHaveText('Visit saved');
  await expect(button).toBeDisabled();
  const saved = await button.boundingBox();
  expect(saved!.width).toBe(before!.width);
  expect(saved!.height).toBe(before!.height);
  await page.locator('#checkin').evaluate(form => (form as HTMLFormElement).requestSubmit());
  await expect(page.locator('.history article')).toHaveCount(1);
  await expect(page.locator('#notice')).toBeEmpty();
  await expect(button).toHaveText('Save check-in', { timeout: 6000 });
  await expect(button).toBeEnabled();
  await page.getByLabel('Notes', { exact: false }).fill('Keep my unfinished draft');
  const form = await page.locator('#checkin').elementHandle();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Delete', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Visit deleted', exact: true })).toBeDisabled();
  await expect(page.locator('.history')).toContainText('Retain this visit during confirmation');
  await expect(page.locator('#visit-count')).toHaveText('0');
  expect(await form!.evaluate(node => node.isConnected)).toBe(true);
  await expect(page.getByLabel('Notes', { exact: false })).toHaveValue('Keep my unfinished draft');
  await page.screenshot({ path: testInfo.outputPath('deleted-visit.png') });
  await expect(page.locator('.history article')).toHaveCount(0, { timeout: 6000 });
  await expect(page.locator('.history')).toContainText('Your first visit is still ahead of you.');
  await expect(page.locator('#notice')).toBeEmpty();
});
