import { expect, test } from '@playwright/test';

test('map background clears selection while markers and map navigation preserve it', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop-chromium', 'Mobile details cover the map.');
  await page.goto('/');
  const map = page.locator('#map');
  const skagit = page.locator('.leaflet-marker-icon[title^="KBVS "]');
  const bellingham = page.locator('.leaflet-marker-icon[title^="KBLI "]');
  await page.getByRole('combobox', { name: 'Region', exact: true }).selectOption('northwest');
  await page.getByRole('button', { name: 'Show all matches' }).click();
  await page.locator('[data-airport="KBVS"]').click();
  await expect(skagit.locator('.is-selected')).toHaveCount(1);
  await bellingham.locator('.passport-marker').click();
  await expect(bellingham.locator('.is-selected')).toHaveCount(1);
  await expect(skagit.locator('.is-selected')).toHaveCount(0);
  await expect(page.locator('#detail')).toBeVisible();
  await page.getByRole('button', { name: 'Save check-in' }).click();
  await expect(bellingham.locator('.is-visited')).toHaveCount(1);

  await map.scrollIntoViewIfNeeded();
  const bounds = (await map.boundingBox())!;
  await page.mouse.move(bounds.x + 60, bounds.y + 100);
  await page.mouse.down();
  await page.mouse.move(bounds.x + 120, bounds.y + 160, { steps: 10 });
  await page.mouse.up();
  await expect(bellingham.locator('.is-selected')).toHaveCount(1);
  await page.getByRole('button', { name: 'Zoom in', exact: true }).click();
  await expect(bellingham.locator('.is-selected')).toHaveCount(1);
  // Wait for Leaflet's pan/zoom animation before comparing the map position.
  await expect(page.locator('.leaflet-zoom-anim, .leaflet-pan-anim')).toHaveCount(0);
  const position = await bellingham.boundingBox();
  const region = await bellingham.locator('.passport-marker').getAttribute('style');
  await map.click({ position: { x: 30, y: 100 } });
  await expect(page.locator('#detail')).toBeHidden();
  await expect(page.locator('.passport-marker.is-selected')).toHaveCount(0);
  await expect(page.locator('.airport-card[aria-pressed="true"]')).toHaveCount(0);
  await expect(page.locator('.browse')).toBeVisible();
  await expect(bellingham.locator('.is-visited')).toHaveCount(1);
  await expect(bellingham.locator('.passport-marker')).toHaveAttribute('style', region!);
  expect(await bellingham.boundingBox()).toEqual(position);
  await expect(map).toBeFocused();
  await map.click({ position: { x: 30, y: 100 } });
  await expect(page.locator('#detail')).toBeHidden();
});

test('map, themes, filters, visits, persistence, and backup work on desktop and mobile', async ({ page }, testInfo) => {
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Fly Washington', exact: true })).toBeVisible();
  await expect(page.locator('.passport-marker')).toHaveCount(115);
  await expect(page.locator('#map')).toHaveClass(/compact-markers/);
  await expect(page.locator('.region-card')).toHaveCount(7);
  await page.getByLabel('Appearance', { exact: true }).selectOption('dark');
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await page.getByLabel('Appearance', { exact: true }).selectOption('light');
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('searchbox', { name: 'Search airports' }).fill('skagit');
  await page.getByRole('button', { name: 'Show all matches' }).click();
  await expect(page.locator('#map')).not.toHaveClass(/compact-markers/);
  await page.locator('.leaflet-marker-icon').filter({ has: page.locator('.passport-marker') }).first().click();
  await expect(page.getByRole('heading', { name: 'Skagit Regional', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'All airports' }).click();
  if (testInfo.project.name.startsWith('mobile')) await page.getByRole('button', { name: 'List', exact: true }).click();
  await page.getByRole('searchbox', { name: 'Search airports' }).fill('skagit');
  await expect(page.locator('.airport-card')).toHaveCount(1);
  await expect(page.locator('.passport-marker')).toHaveCount(1);
  await page.locator('.airport-card').click();
  await expect(page.getByRole('heading', { name: 'Skagit Regional', exact: true })).toBeVisible();
  await expect(page.locator('.stamp')).toHaveCount(1);
  await expect(page.locator('.stamp')).toContainText('Port of Skagit');
  await page.getByLabel('Visit date').fill('2026-08-10');
  await page.getByLabel('Notes', { exact: false }).fill('First flight <script>safe text</script>');
  await page.getByRole('button', { name: 'Save check-in' }).click();
  await expect(page.locator('.history article')).toHaveCount(1);
  await expect(page.locator('.passport-marker.is-visited')).toHaveCount(1);
  await page.reload();
  if (testInfo.project.name.startsWith('mobile')) await page.getByRole('button', { name: 'List', exact: true }).click();
  await page.locator('#airport-list').getByRole('button', { name: /KBVS.*Skagit Regional/ }).click();
  await expect(page.locator('.history')).toContainText('First flight <script>safe text</script>');
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  await page.getByLabel('Notes', { exact: false }).fill('Updated visit');
  await page.getByRole('button', { name: 'Save changes' }).click();
  await expect(page.locator('.history')).toContainText('Updated visit');
  await page.getByRole('button', { name: 'All airports' }).click();
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export passport' }).click();
  const download = await downloadEvent;
  const path = testInfo.outputPath('passport.json'); await download.saveAs(path);
  await page.locator('#airport-list').getByRole('button', { name: /KBVS.*Skagit Regional/ }).click();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Delete', exact: true }).click();
  await expect(page.locator('.history article')).toHaveCount(0);
  await page.getByRole('button', { name: 'All airports' }).click();
  await page.locator('#import').setInputFiles(path);
  await expect(page.locator('#notice')).toContainText('Imported 1 visits');
  await page.locator('#import').setInputFiles(path);
  await expect(page.locator('#notice')).toContainText('Imported 0 visits');
  await page.getByRole('combobox', { name: 'Passport', exact: true }).selectOption('visited');
  await expect(page.locator('.airport-card')).toHaveCount(1);
  await page.screenshot({ path: testInfo.outputPath('passport-light.png'), fullPage: true });
  await page.getByLabel('Appearance', { exact: true }).selectOption('dark');
  await page.screenshot({ path: testInfo.outputPath('passport-dark.png'), fullPage: true });
});

test('real regions filter both views and actual multiple stamp locations are available', async ({page},testInfo) => {
  await page.goto('/');
  if (testInfo.project.name.startsWith('mobile')) await page.getByRole('button',{name:'List',exact:true}).click();
  await page.getByRole('combobox',{name:'Region',exact:true}).selectOption('seaplane-bases');
  await expect(page.locator('.airport-card')).toHaveCount(4);
  await expect(page.locator('.passport-marker')).toHaveCount(4);
  await page.getByRole('combobox',{name:'Region',exact:true}).selectOption('olympic');
  await expect(page.locator('.airport-card')).toHaveCount(19);
  await page.getByRole('searchbox',{name:'Search airports'}).fill('Bremerton');
  await page.locator('.airport-card').click();
  await expect(page.locator('.stamp')).toHaveCount(2);
  await expect(page.locator('#detail')).toContainText('Avian Flight Center');
  await expect(page.locator('#detail')).toContainText('Pilot lounge');
});

test('installed app shell opens and saves visits offline without caching map tiles', async ({ page, context, browserName }, testInfo) => {
  // Reproduced on Windows/WebKit 2359: CacheStorage is readable and online
  // navigation is served by the worker, but setOffline makes navigation fail
  // inside WebKit. Keep this visible; Linux CI must still pass this scenario.
  test.fail(process.platform === 'win32' && browserName === 'webkit', 'Windows WebKit offline navigation fails internally; physical iPhone verification remains open.');
  await page.goto('/');
  await page.evaluate(async () => { await navigator.serviceWorker.ready; });
  await page.reload();
  await expect.poll(() => page.evaluate(() => !!navigator.serviceWorker.controller)).toBe(true);
  await context.setOffline(true);
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Fly Washington', exact: true })).toBeVisible();
  if (testInfo.project.name.startsWith('mobile')) await page.getByRole('button', { name: 'List', exact: true }).click();
  await page.locator('#airport-list').getByRole('button', { name: /KORS.*Orcas Island/ }).click();
  await page.getByRole('button', { name: 'Save check-in' }).click();
  await expect(page.locator('.history article')).toHaveCount(1);
  const urls = await page.evaluate(async () => (await Promise.all((await caches.keys()).map(async key => (await (await caches.open(key)).keys()).map(request => request.url)))).flat());
  expect(urls.some(url => url.includes('tile.openstreetmap.org'))).toBe(false);
});
